{config, ...}: {
  programs.eww = {
    enable = true;
  };

  xdg.configFile."eww" = {
    source = ./config;
    recursive = true;
  };

  xdg.configFile."eww/stylix.scss".text = with config.lib.stylix.colors.withHashtag;
  #scss
    ''
      // Base16 colours (generated by stylix for eww)
      $bg-alt   : ${base00}; // base00
      $bg       : ${base01}; // base01
      $sel      : ${base02}; // base02
      $invi     : ${base03}; // base03
      $fg-alt   : ${base04}; // base04
      $fg       : ${base05}; // base05
      $fg-light : ${base06}; // base06
      $bg-light : ${base07}; // base07
      $red      : ${base08}; // base08
      $orange   : ${base09}; // base09
      $yellow   : ${base0A}; // base0A
      $green    : ${base0B}; // base0B
      $cyan     : ${base0C}; // base0C
      $blue     : ${base0D}; // base0D
      $Purple   : ${base0E}; // base0E
      $Brown    : ${base0F}; // base0F
    '';
}
