{
  inputs,
  config,
  ...
}: {
  imports = [
    inputs.vicinae.homeManagerModules.default
  ];

  services.vicinae = {
    enable = true;
    autoStart = true;
  };

  # Stylix theming for vicinae
  xdg.configFile."vicinae/themes/stylix.json".text = with config.lib.stylix.colors.withHashtag; ''
    {
    	"version": "1.0.0",
    	"appearance": "${config.stylix.polarity}",
    	"icon": "",
    	"name": "stylix theme",
    	"description": "Custom theme file generated by stylix",
    	"palette": {
    	  "background": "${base00}",
    	  "foreground": "${base05}",
    	  "blue": "${base0D}",
    	  "green": "${base0B}",
    	  "magenta": "${base0E}",
    	  "orange": "${base09}",
    	  "purple": "${base0E}",
    	  "red": "${base08}",
    	  "yellow": "${base0A}",
    	  "cyan": "${base0C}"
    	}
    }
  '';
}
